sherlockode_crud:
    crud:
        animal:
            config:
                class: App\Entity\Animal
                form: App\Form\Type\AnimalType
            grid:
                filters:
                    name:
                        type: string
                fields:
                    name:
                        sortable: ~
                actions:
                    update: ~
                    delete: ~
                settings:
                    page_size: 20
        breed:
            config:
                class: App\Entity\Breed
                form: App\Form\Type\BreedType
            grid:
                filters:
                    label:
                        type: string
                fields:
                    label:
                        sortable: ~
                actions:
                    update: ~
                    delete: ~
                settings:
                    page_size: 20

        species:
            config:
                class: App\Entity\Species
                form: App\Form\Type\SpeciesType
            grid:
                filters:
                    label:
                        type: string
                fields:
                    label:
                        sortable: ~
                actions:
                    update: ~
                    delete: ~
                settings:
                    page_size: 20
